using System.Collections.Generic;
using UnityEngine;
/// <summary>
/// The primary data packet containing the context of an action before effects are applied.
/// Generated by SkillCastState.
/// </summary>
public struct EffectPayload
{
	[Header("Core Context")]
	public GameObject User;
	public GameObject Target;
	public Vector3 TargetPosition;

	[Header("Hit Data")]
	public Vector2 HitDirection;
	public Vector2 HitImpactPoint;
	public float HitImpact;
	public HashSet<IDamagable> HitTargets;
	public bool IsBonusHit;

	[Header("Skill Data")]
	public SkillDataInstance SkillDataInstance;
	public float SkillDamageBase;

	public EffectPayload(GameObject user) : this()
	{
		User = user;
	}
}

/// <summary>
/// Carries the compiled SkillDataInstance data for a skill.
/// Compiled by SkillCastState -> Projectile -> HitBox.
/// </summary>
public struct CombatContext
{
	public GameObject User;
	public SkillDataInstance SkillDataInstance;
	public float SkillDamageBase;
	public List<Effect> EffectsList;
	public bool IsBonusHit;
}

/// <summary>
/// Settings for the hitbox of a skill.
/// </summary>
public struct HitBoxSettings
{
	public int MaxEnemiesHit;
	public bool HitOncePerTarget;
	public bool DestroyOnMaxHits;
	public float HitImpact;
	public HashSet<IDamagable> InheritedTargetsList;
}

/// <summary>
/// Settings for the projectile trajectory of a skill.
/// </summary>
public struct ProjectileFlightData
{
	public Vector3 TargetPosition;
	public float Speed;
	public float Duration;
	public float MaxHeight;
	public AnimationCurve Curve;
	public float Scale;
}

/// <summary>
/// Final calculated damage data passed to an Entity's health system.
/// </summary>
public enum DamageType { Physical, Fire, Water, Earth, Lightning, Holy, Shadow }

public struct DamageData
{
	public float Amount;
	public Vector2 Direction;
	public Vector2 ImpactPoint;
	public float KnockbackForce;
	public float KnockbackDuration;
	public float KnockbackHeight;
	public DamageType Type;
	public GameObject Source;
	public bool IsBonusHit;
	public float InvulnerableTimer;
}
